export type CampaignMode='title'|'play'|'win'|'lose';
const DOCS:Record<number,string[]>={
 5:['APPOINTMENT BOOK — Fiona was seen by a doctor who does not exist on staff.','PRESCRIPTION PAD — The same compound, signed three different ways.','AUTHORIZATION SLIP — A director’s signature, dated before the consent form.'],
 6:['EXPERIMENT LOG — Subject seven stopped responding on the fourth night.','SAMPLE MANIFEST — Two vials left the building unrecorded.','CLINICAL NOTE — “Discontinue observation. Move her downstairs.”'],
 7:['STORAGE INVENTORY — A bed was signed out to a room with no number.','MAINTENANCE SLIP — The basement lights were cut on purpose.','PATIENT BAND — The name on it is Fiona’s.'],
 8:['SERVER TICKET — Backups were wiped from a terminal in this room.','ACCESS LOG — Someone signed in as Fiona after she disappeared.','MAIL DRAFT — “If this gets out, we are all finished.”'],
 9:['DESK MEMO — The director approved every transfer personally.','SEALED FOLDER — Saint Cross has done this eleven times before.','SIGNED AUTHORIZATION — The proof, in his own handwriting.'],
};
export class CampaignWorld{readonly stage:number;readonly width=1700;readonly height=540;readonly floorY=410;readonly playerHalfWidth=18;readonly playerHalfHeight=44;cameraX=0;mode:CampaignMode='title';time=0;stealth=100;suspicion=0;progress=0;note='';muted=false;demo=false;player={x:90,y:366,vy:0,facing:1,hidden:false,running:false};guard={x:1260,dir:-1};journal:string[]=[];evidence=0;key=false;laserDisabled=false;uploading=false;rescued=false;switchOn=false;alarm=0;target=0;
 constructor(stage:number){this.stage=stage;this.configure();}
 configure(){const names:any={5:'Find the laser control box.',6:'Recover the experiment log and sample.',7:'Find the light switch and search the dark storage.',8:'Reach the server terminal and upload the truth.',9:'Take the signed authorization and escape to the roof.'};this.note=names[this.stage]||'Continue the investigation.';this.target=this.stage===8?60:0;}
 start(demo=false){this.demo=demo;this.reset();}reset(){this.mode='play';this.time=0;this.stealth=100;this.suspicion=0;this.progress=0;this.evidence=0;this.key=false;this.laserDisabled=false;this.uploading=false;this.rescued=false;this.switchOn=false;this.alarm=0;this.player={x:90,y:366,vy:0,facing:1,hidden:false,running:false};this.cameraX=0;this.journal=[];this.guard={x:1260,dir:-1};this.configure();}
 evidenceCount(){return this.evidence;}hasKey(){return this.key;}near(x:number){return Math.abs(this.player.x-x)<90&&!this.player.hidden;}
 press(key:string){const k=key.toLowerCase();if(k==='m'){this.muted=!this.muted;return;}if(this.mode!=='play')return;this.keys.add(k);if(k==='e'&&this.stage!==8&&!this.player.hidden&&this.player.x>250&&this.player.x<430)this.player.hidden=!this.player.hidden;if(k==='l'&&this.stage===7&&this.near(480)){this.switchOn=true;this.note='LIGHTS ON — the torches can see you now.';}if(k==='u'&&this.stage===8&&this.near(850)&&!this.uploading){this.uploading=true;this.note='UPLOAD IN PROGRESS — stay at the terminal.';}if(k==='x'&&this.stage===5&&this.near(520)){this.laserDisabled=true;this.note='LASER CONTROL DISABLED — cross the office.';}if(k==='r'&&this.stage===7&&this.near(1120)){this.rescued=true;this.note='PATIENT LOCATED — guide them to the service door.';}}
 release(key:string){this.keys.delete(key.toLowerCase());}keys=new Set<string>();
 step(dt:number){if(this.mode!=='play')return;this.time+=dt;if(this.demo)this.runDemo();const l=this.keys.has('a')||this.keys.has('arrowleft');const r=this.keys.has('d')||this.keys.has('arrowright');const run=this.keys.has('shift');this.player.running=run;if(!this.player.hidden){const axis=(r?1:0)-(l?1:0);this.player.x+=axis*(run?190:112)*dt;if(axis)this.player.facing=axis;if((this.keys.has(' ')||this.keys.has('w'))&&this.player.y>=this.floorY-this.playerHalfHeight)this.player.vy=-245;this.player.vy+=700*dt;this.player.y+=this.player.vy*dt;if(this.player.y>this.floorY-this.playerHalfHeight)this.player.y=this.floorY-this.playerHalfHeight,this.player.vy=0;}this.player.x=Math.max(35,Math.min(1635,this.player.x));const cameraTarget=Math.max(0,Math.min(740,this.player.x-350));this.cameraX+=(cameraTarget-this.cameraX)*Math.min(1,dt*8);
  if(this.stage===8&&this.uploading){if(Math.abs(this.player.x-850)>36)this.uploading=false;else this.progress=Math.min(60,this.progress+dt);this.note=this.progress>=60?'UPLOAD COMPLETE — reach the roof relay.':'UPLOAD IN PROGRESS — stay at the terminal.';}
  this.guard.x+=this.guard.dir*(this.stage===8?92:66)*dt;if(this.guard.x<1080){this.guard.x=1080;this.guard.dir=1;}if(this.guard.x>1500){this.guard.x=1500;this.guard.dir=-1;}const dist=Math.abs(this.player.x-this.guard.x);const sees=!this.player.hidden&&dist<(this.stage===8?290:210)&&Math.sign(this.player.x-this.guard.x)===this.guard.dir;const heard=!this.player.hidden&&this.player.running&&dist<(this.stage===8?200:160);if(sees||heard){this.suspicion=Math.min(100,this.suspicion+dt*(this.stage===8?28:18));this.note=this.stage===8?'ELITE GUARD HEARD YOU — keep the upload alive.':'SECURITY ALERT — find cover.';}else this.suspicion=Math.max(0,this.suspicion-dt*10);this.stealth=Math.max(0,100-this.suspicion);
  const checkpoints=[320,700,1080];for(let i=0;i<checkpoints.length;i++){if(this.player.x>=checkpoints[i]&&this.evidence<i+1){this.evidence=i+1;const label=DOCS[this.stage]?.[i];if(label){this.journal.push(label);this.note=label;}}}if(this.stage===5&&!this.laserDisabled&&this.player.x>620&&this.player.x<930)this.suspicion=Math.min(100,this.suspicion+dt*24);if(this.stage===5&&this.laserDisabled&&this.player.x>1050)this.key=true;if(this.stage===6&&this.player.x>1370)this.key=true;if(this.stage===7&&this.switchOn&&this.player.x>1450)this.key=true;if(this.stage===7&&this.rescued&&this.player.x>1500)this.progress=1;if(this.stage===9&&this.player.x>850)this.key=true;if(this.stage===9&&this.player.x>1200)this.alarm=Math.min(60,this.alarm+dt);if(this.stage===9&&this.alarm>0)this.note=`ROOF RUN — ${Math.ceil(60-this.alarm)} seconds remain.`;if(this.suspicion>=100||this.alarm>=60){this.mode='lose';this.note='The building locks down before you can escape.';}
  const complete=this.stage===5?this.laserDisabled&&this.key&&this.evidence>=2&&this.player.x>1530:this.stage===6?this.evidence>=3&&this.key&&this.player.x>1530:this.stage===7?this.switchOn&&this.rescued&&this.player.x>1550:this.stage===8?this.progress>=60&&this.player.x>1500:this.key&&this.player.x>1550;if(complete){this.mode='win';this.note=this.stage===9?'THE TRUTH WILL OUT — Finn reaches the roof.':'STAGE COMPLETE — the investigation continues.';}}
 private runDemo(){this.keys.clear();
  if(this.stage===8){if(this.progress<60){if(this.player.x<846)this.keys.add('d');else if(this.player.x>854)this.keys.add('a');else if(!this.uploading)this.press('u');}else if(this.suspicion>45)this.keys.add('a');else if(this.player.x<1550)this.keys.add('d');return;}
  if(this.stage===5&&!this.laserDisabled){this.player.x<520?this.keys.add('d'):this.press('x');return;}
  if(this.stage===7&&!this.switchOn){this.player.x<480?this.keys.add('d'):this.press('l');return;}
  if(this.stage===7&&!this.rescued){this.player.x<1120?this.keys.add('d'):this.press('r');return;}
  if(this.suspicion>45)this.keys.add('a');else if(this.player.x<1550)this.keys.add('d');}
}
