export type VaultMode='title'|'play'|'win'|'lose';
export class VaultWorld{
 readonly width=1600;readonly height=540;readonly floorY=410;readonly playerHalfWidth=18;readonly playerHalfHeight=44;cameraX=0;mode:VaultMode='title';time=0;suspicion=0;stealth=100;muted=false;note='Hack the security camera before crossing the laser grid.';demo=false;escapeActive=false;
 player={x:90,y:366,vy:0,facing:1,hidden:false,running:false};guard={x:1280,dir:-1,state:'patrol' as 'patrol'|'alert'};cameraHacked=false;biometric=false;doorOverridden=false;laserPhase=0;
 pickups=[{x:360,kind:'evidence' as const,label:'VAULT LOG — The lock recognizes a living pulse, not a keycard.',taken:false},{x:730,kind:'evidence' as const,label:'CAMERA TRACE — Remote overrides route through the old monitor.',taken:false},{x:1120,kind:'evidence' as const,label:'ACCESS NOTE — The vault opens for one minute after a clean scan.',taken:false},{x:1400,kind:'key' as const,label:'VAULT TOKEN — Fiona’s file is stored behind the blast door.',taken:false}];keys=new Set<string>();
 start(demo=false){this.demo=demo;this.mode='play';this.reset();}reset(){this.mode='play';this.time=0;this.suspicion=0;this.stealth=100;this.escapeActive=false;this.note='Hack the security camera before crossing the laser grid.';this.player={x:90,y:366,vy:0,facing:1,hidden:false,running:false};this.guard={x:1280,dir:-1,state:'patrol'};this.cameraHacked=false;this.biometric=false;this.doorOverridden=false;this.pickups.forEach(p=>p.taken=false);}
 evidenceCount(){return this.pickups.filter(p=>p.kind==='evidence'&&p.taken).length;}hasKey(){return this.pickups.some(p=>p.kind==='key'&&p.taken);}nearCamera(){return Math.abs(this.player.x-540)<90&&!this.player.hidden;}nearBio(){return Math.abs(this.player.x-980)<90&&!this.player.hidden;}nearDoor(){return this.player.x>1350;}
 press(key:string){const k=key.toLowerCase();if(k==='m'){this.muted=!this.muted;return;}if(this.mode!=='play')return;this.keys.add(k);if(k==='e'&&this.mode==='play'&&this.player.x>250&&this.player.x<430)this.player.hidden=!this.player.hidden;if(k==='h'&&this.nearCamera()){this.cameraHacked=true;this.note='CAMERA OVERRIDE ACTIVE — the laser timing is visible.';}if(k==='b'&&this.nearBio()){this.biometric=true;this.note='BIOMETRIC ACCEPTED — pulse matched to the vault registry.';}if(k==='r'&&this.nearDoor()&&this.biometric){this.doorOverridden=true;this.note='REMOTE DOOR OVERRIDE — the blast door is cycling.';}}
 release(key:string){this.keys.delete(key.toLowerCase());}
 step(dt:number){if(this.mode!=='play')return;this.time+=dt;this.laserPhase=(this.time%4.2)/4.2;if(this.demo)this.runDemo();const l=this.keys.has('a')||this.keys.has('arrowleft');const r=this.keys.has('d')||this.keys.has('arrowright');const run=this.keys.has('shift');this.player.running=run;if(!this.player.hidden){const axis=(r?1:0)-(l?1:0);this.player.x+=axis*(run?185:110)*dt;if(axis)this.player.facing=axis;if((this.keys.has(' ')||this.keys.has('w')||this.keys.has('arrowup'))&&this.player.y>=this.floorY-this.playerHalfHeight)this.player.vy=-245;this.player.vy+=700*dt;this.player.y+=this.player.vy*dt;if(this.player.y>this.floorY-this.playerHalfHeight)this.player.y=this.floorY-this.playerHalfHeight,this.player.vy=0;}this.player.x=Math.max(35,Math.min(1590,this.player.x));const cameraTarget=Math.max(0,Math.min(640,this.player.x-350));this.cameraX+=(cameraTarget-this.cameraX)*Math.min(1,dt*8);this.guard.x+=this.guard.dir*68*dt;if(this.guard.x<1120){this.guard.x=1120;this.guard.dir=1;}if(this.guard.x>1480){this.guard.x=1480;this.guard.dir=-1;}const sees=!this.player.hidden&&Math.abs(this.player.x-this.guard.x)<240&&Math.sign(this.player.x-this.guard.x)===this.guard.dir;if(sees||this.player.running&&Math.abs(this.player.x-this.guard.x)<180){this.guard.state='alert';this.suspicion=Math.min(100,this.suspicion+dt*34);this.note='VAULT SECURITY ALERT — use the maintenance shadow.';}else{this.guard.state='patrol';this.suspicion=Math.max(0,this.suspicion-dt*14);}this.stealth=Math.max(0,100-this.suspicion);if(!this.cameraHacked&&this.player.x>470&&this.player.x<670&&!this.player.hidden)this.suspicion=Math.min(100,this.suspicion+dt*8);if(!this.cameraHacked&&this.player.x>670&&this.player.x<900)this.note='LASER GRID — hack the camera with H.';if(this.cameraHacked&&this.player.x>670&&this.player.x<900){const safe=this.laserPhase<.42||this.laserPhase>.72;if(!safe&&!this.player.hidden)this.suspicion=Math.min(100,this.suspicion+dt*26);this.note=safe?'LASER GAP OPEN — cross now.':'LASER GRID ACTIVE — wait for the gap.';}if(this.nearBio()&&!this.biometric)this.note='BIOMETRIC LOCK — press B to scan.';if(this.doorOverridden&&!this.escapeActive)this.note='REMOTE OVERRIDE ACTIVE — reach the open blast door.';this.pickups.forEach(p=>{if(!p.taken&&Math.abs(this.player.x-p.x)<this.playerHalfWidth+10){p.taken=true;this.note=p.label;}});if(this.suspicion>=100){this.mode='lose';this.note='Vault security seals the level.';}if(this.doorOverridden&&this.hasKey()&&this.evidenceCount()===3&&this.player.x>1500){this.escapeActive=true;this.note='FINAL ESCAPE — run for the service tunnel.';}if(this.escapeActive&&this.player.x>1570){this.mode='win';this.note='THE VAULT OPENS — Finn escapes with Fiona’s file.';}}
 private runDemo(){this.keys.clear();if(!this.cameraHacked&&this.player.x<540-20)this.keys.add('d');else if(!this.cameraHacked){this.press('h');}else if(!this.biometric&&this.player.x<980-20)this.keys.add('d');else if(!this.biometric){this.press('b');}else if(!this.doorOverridden&&this.player.x<1400-20)this.keys.add('d');else if(!this.doorOverridden){this.press('r');}else{const target=this.pickups.find(p=>!p.taken)?.x??1590;if(this.player.x<target-8)this.keys.add('d');else if(this.player.x>target+8)this.keys.add('a');}}
}
